### ISSUE TITLE
require('billboard.js') with webpack and vue

### ISSUE THREAD

**Issue by martin-181** [naver/billboard.js#194]
## Description
Hi all,
I'm trying to get billboard.js to get working with vue (2.0) inside webpack.
When running `npm run dev` to get the dev server running, an error occurs:
`[Vue warn]: Error in mounted hook: "TypeError: bb.generate is not a function`

## Steps to check or reproduce
Mockup code example:

```
<template>
  <div id='bbPlot'></div>
</template>
<script>
const bb = require('billboard.js')
bb.generate({....})
</script>
```

Thanks in advance for any help/suggestions,
Martin

**Comment by psi-4ward** [comment]
I assume youre using ES6 module support within babel so try: `import {bb} from 'billboard.js'`

**Comment by netil** [comment]
Or try using `vue-billboard`
- https://github.com/meman/vue-billboard

**Comment by martin-181** [comment]
@psi-4ward  the `{bb}` syntax solved the issue :)
@netil I will also have a look at vue-billboard
Thank you for your support.
